USER_ID="Stiffler"
REGION="ap-south-1"
ACCESS_KEY="AKIA4MWYQZUREOVYM3VG"
SECRET_KEY="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"
INSTANCE_NAME="mern"
EC2_INSTANCE_TYPE="t2.micro"
AMI="ami-03f4878755434977f"

./deleteEC2.sh $USER_ID $INSTANCE_NAME $EC2_INSTANCE_TYPE $AMI.