USER_ID="Stiffler"
REGION="ap-south-1"
ACCESS_KEY="AKIA4MWYQZURHFUP3DHV"
SECRET_KEY="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"
INSTANCE_NAME="mern"
EC2_INSTANCE_TYPE="t2.micro"
AMI="ami-03f4878755434977f"

./terraformInit.sh $USER_ID $REGION $ACCESS_KEY $SECRET_KEY
./provisionEC2.sh $USER_ID $INSTANCE_NAME $EC2_INSTANCE_TYPE $AMI